"""Conformance tests: bot/cord.py must match Armada's derive.ts byte-for-byte.

vectors.json is generated by running Armada's ACTUAL TypeScript
(client/src/concord-v2/lib/derive.ts) via scratch script gen-vectors.mts —
regenerate it if the wire format ever changes (it shouldn't; it's frozen).
"""

import json
from pathlib import Path

from bot.cord import (
    channel_group_key,
    community_id_of,
    control_group_key,
    epoch_key_commitment,
    grant_locator,
    guestbook_group_key,
    invite_bundle_key,
    verify_community_id,
    voice_group_key,
    voice_media_key,
    voice_sender_key,
)

A = bytes([1] * 32)
B = bytes([2] * 32)
C = bytes([3] * 32)

VECTORS = json.loads((Path(__file__).parent / "vectors.json").read_text())


class TestArmadaVectors:
    def test_channel_group_key(self):
        gk = channel_group_key(A, B, 0)
        want = VECTORS["channel_group_A_B_0"]
        assert gk.sk.hex() == want["sk"]
        assert gk.pk == want["pk"]
        assert gk.conv_key.hex() == want["conv_key"]

    def test_channel_group_key_epoch_1(self):
        assert channel_group_key(A, B, 1).pk == VECTORS["channel_group_A_B_1_pk"]

    def test_control_and_guestbook(self):
        assert control_group_key(A, B, 0).pk == VECTORS["control_group_A_B_0_pk"]
        assert guestbook_group_key(A, B, 0).pk == VECTORS["guestbook_group_A_B_0_pk"]

    def test_voice_group_key(self):
        gk = voice_group_key(A, B, 0)
        assert gk.sk.hex() == VECTORS["voice_group_A_B_0"]["sk"]
        assert gk.pk == VECTORS["voice_group_A_B_0"]["pk"]

    def test_voice_media_key(self):
        assert voice_media_key(A, B, 0).hex() == VECTORS["voice_media_A_B_0"]
        assert voice_media_key(A, B, 1).hex() == VECTORS["voice_media_A_B_1"]

    def test_voice_sender_key(self):
        media = voice_media_key(A, B, 0)
        assert voice_sender_key(media, "00112233445566778899aabbccddeeff").hex() \
            == VECTORS["voice_sender_hexid"]
        assert voice_sender_key(media, "alice-identity").hex() == VECTORS["voice_sender_alice"]

    def test_locators_and_commitments(self):
        assert grant_locator(A, B).hex() == VECTORS["grant_locator_A_B"]
        assert invite_bundle_key(bytes([7] * 16)).hex() == VECTORS["invite_bundle_key_7x16"]
        assert community_id_of(A, B).hex() == VECTORS["community_id_A_B"]
        assert epoch_key_commitment(2, A).hex() == VECTORS["epoch_commitment_2_A"]


class TestProperties:
    def test_distinct_per_label(self):
        pks = {channel_group_key(A, B, 0).pk, control_group_key(A, B, 0).pk,
               guestbook_group_key(A, B, 0).pk, voice_group_key(A, B, 0).pk}
        assert len(pks) == 4

    def test_epoch_and_id_separation(self):
        assert channel_group_key(A, B, 0).pk != channel_group_key(A, B, 1).pk
        assert channel_group_key(A, B, 0).pk != channel_group_key(A, C, 0).pk
        assert voice_group_key(A, C, 0).pk != voice_group_key(A, B, 0).pk

    def test_sender_keys_partition(self):
        media = voice_media_key(A, B, 0)
        assert voice_sender_key(media, "a") != voice_sender_key(media, "b")
        assert voice_sender_key(media, "a") != media

    def test_verify_community_id(self):
        cid = community_id_of(A, B).hex()
        assert verify_community_id(cid, A.hex(), B.hex())
        assert not verify_community_id(cid, C.hex(), B.hex())
        assert not verify_community_id(cid, "nothex", B.hex())
