"""CORD-02 Appendix A primitives + CORD-07 voice derivations.

Byte-exact port of Armada's client/src/concord-v2/lib/derive.ts (the frozen
wire format). Every labeled byte here re-addresses prior events if changed —
treat as wire format. Conformance is asserted against vectors generated by
running Armada's actual TypeScript (bot/tests/vectors.json).

Construction (A.1): HKDF-SHA256(ikm=secret, salt=∅, info, L=32) where
  info = utf8(label) || 0x00 || id[32] || epoch_be[8]?
The id is always present (all-zeroes where a label has no meaningful id); the
epoch is the only omittable field. The scalar_normalize retry counter (A.3)
appends after whatever fields are present, starting at byte 0.
"""

from __future__ import annotations

import hashlib
import hmac
from dataclasses import dataclass

from coincurve import PrivateKey, PublicKey

# secp256k1 group order (valid secret scalars are 1..N-1)
_SECP256K1_N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

LABEL_CHANNEL = "concord/channel"
LABEL_CONTROL = "concord/control"
LABEL_GUESTBOOK = "concord/guestbook"
LABEL_VOICE_SIGNER = "concord/voice-signer"
LABEL_VOICE_MEDIA = "concord/voice-media"
LABEL_VOICE_SENDER = "concord/voice-sender"
LABEL_GRANT = "concord/grant"
LABEL_BANLIST = "concord/banlist"
LABEL_INVITE_KEY = "concord/invite-key"
LABEL_COMMUNITY = "concord/community"          # A.4: plain SHA-256 prefix, not HKDF
LABEL_EPOCH_COMMITMENT = "concord/epoch-key-commitment"  # A.5

ZERO32 = bytes(32)


def _hkdf_sha256(ikm: bytes, info: bytes, length: int = 32) -> bytes:
    """RFC 5869 HKDF-SHA256 with zero-length salt (== HashLen zeros under HMAC)."""
    prk = hmac.new(b"", ikm, hashlib.sha256).digest()
    out = b""
    t = b""
    counter = 1
    while len(out) < length:
        t = hmac.new(prk, t + info + bytes([counter]), hashlib.sha256).digest()
        out += t
        counter += 1
    return out[:length]


def build_info(label: str, id32: bytes, epoch: int | None = None) -> bytes:
    """A.1 frozen info layout: utf8(label) || 0x00 || id[32] || epoch_be[8]?"""
    if len(id32) != 32:
        raise ValueError(f"id must be 32 bytes, got {len(id32)}")
    info = label.encode() + b"\x00" + id32
    if epoch is not None:
        info += epoch.to_bytes(8, "big")
    return info


def hkdf32(ikm: bytes, info: bytes) -> bytes:
    return _hkdf_sha256(ikm, info, 32)


def _is_valid_scalar(seed: bytes) -> bool:
    n = int.from_bytes(seed, "big")
    return 0 < n < _SECP256K1_N


def _hkdf_to_secret_key(ikm: bytes, base_info: bytes) -> bytes:
    """A.3 scalar_normalize: retry with one appended counter byte, starting at 0."""
    seed = hkdf32(ikm, base_info)
    if _is_valid_scalar(seed):
        return seed
    for counter in range(0x100):
        seed = hkdf32(ikm, base_info + bytes([counter]))
        if _is_valid_scalar(seed):
            return seed
    raise RuntimeError("scalar rejection 257 times running is impossible")


def xonly_pubkey(sk: bytes) -> bytes:
    """BIP-340 x-only public key (the x coordinate; parity-independent)."""
    return PublicKey.from_valid_secret(sk).format(compressed=True)[1:33]


def nip44_conversation_key(sk: bytes, pk_xonly: bytes) -> bytes:
    """NIP-44 v2 conversation key: hkdf_extract(salt="nip44-v2", ikm=ECDH_x(sk, pk))."""
    point = PublicKey(b"\x02" + pk_xonly)  # lift_x, even Y
    shared = point.multiply(sk).format(compressed=True)[1:33]
    return hmac.new(b"nip44-v2", shared, hashlib.sha256).digest()


@dataclass(frozen=True)
class GroupKey:
    """A plane's stream keypair (A.2): pk is the on-wire Stream address (hex),
    sk signs its wraps, conv_key (NIP-44 self-ECDH) encrypts them."""
    sk: bytes
    pk: str
    conv_key: bytes


def group_key(label: str, secret: bytes, id32: bytes, epoch: int | None = None) -> GroupKey:
    sk = _hkdf_to_secret_key(secret, build_info(label, id32, epoch))
    pk = xonly_pubkey(sk)
    return GroupKey(sk=sk, pk=pk.hex(), conv_key=nip44_conversation_key(sk, pk))


def _assert32(name: str, b: bytes) -> None:
    if len(b) != 32:
        raise ValueError(f"{name} must be 32 bytes, got {len(b)}")


# ── Plane keys (CORD-02 §5, CORD-03 §1) ─────────────────────────────────────

def channel_group_key(secret: bytes, channel_id: bytes, epoch: int) -> GroupKey:
    """The Channel's stream key. secret = community_root (public channel, root
    epoch) or the channel's own key/epoch (private channel)."""
    _assert32("secret", secret)
    _assert32("channel_id", channel_id)
    return group_key(LABEL_CHANNEL, secret, channel_id, epoch)


def control_group_key(community_root: bytes, community_id: bytes, epoch: int) -> GroupKey:
    _assert32("community_root", community_root)
    _assert32("community_id", community_id)
    return group_key(LABEL_CONTROL, community_root, community_id, epoch)


def guestbook_group_key(community_root: bytes, community_id: bytes, epoch: int) -> GroupKey:
    _assert32("community_root", community_root)
    _assert32("community_id", community_id)
    return group_key(LABEL_GUESTBOOK, community_root, community_id, epoch)


# ── Voice sub-keys (CORD-07 §1/§3) ──────────────────────────────────────────

def voice_group_key(secret: bytes, channel_id: bytes, epoch: int) -> GroupKey:
    """voice_key: pk IS the SFU room name; sk signs broker token grants."""
    _assert32("secret", secret)
    _assert32("channel_id", channel_id)
    return group_key(LABEL_VOICE_SIGNER, secret, channel_id, epoch)


def voice_media_key(secret: bytes, channel_id: bytes, epoch: int) -> bytes:
    """The raw 32-byte media root; never feeds a cipher directly."""
    _assert32("secret", secret)
    _assert32("channel_id", channel_id)
    return hkdf32(secret, build_info(LABEL_VOICE_MEDIA, channel_id, epoch))


def voice_sender_key(media_key: bytes, identity: str) -> bytes:
    """Per-sender frame key material: hkdf(media_key, "concord/voice-sender",
    sha256(utf8(identity))) — the epoch field is omitted (media key carries it)."""
    _assert32("media_key", media_key)
    ident_id = hashlib.sha256(identity.encode()).digest()
    return hkdf32(media_key, build_info(LABEL_VOICE_SENDER, ident_id))


# ── Coordinates ──────────────────────────────────────────────────────────────

def grant_locator(community_id: bytes, member_xonly: bytes) -> bytes:
    """A member's Grant entity coordinate (CORD-04) — where role grants live."""
    _assert32("community_id", community_id)
    _assert32("member_xonly", member_xonly)
    return hkdf32(community_id, build_info(LABEL_GRANT, member_xonly))


def banlist_locator(community_id: bytes) -> bytes:
    _assert32("community_id", community_id)
    return hkdf32(community_id, build_info(LABEL_BANLIST, ZERO32))


def invite_bundle_key(token: bytes) -> bytes:
    """The public-invite bundle decrypt key, from the link's unlock token."""
    return hkdf32(token, build_info(LABEL_INVITE_KEY, ZERO32))


# ── A.4 / A.5 commitments ────────────────────────────────────────────────────

def community_id_of(owner_xonly: bytes, owner_salt: bytes) -> bytes:
    """sha256("concord/community" || owner_xonly || owner_salt)."""
    _assert32("owner_xonly", owner_xonly)
    _assert32("owner_salt", owner_salt)
    return hashlib.sha256(LABEL_COMMUNITY.encode() + owner_xonly + owner_salt).digest()


def verify_community_id(community_id_hex: str, owner_hex: str, owner_salt_hex: str) -> bool:
    try:
        return community_id_of(bytes.fromhex(owner_hex), bytes.fromhex(owner_salt_hex)).hex() \
            == community_id_hex.lower()
    except ValueError:
        return False


def epoch_key_commitment(prev_epoch: int, prev_key: bytes) -> bytes:
    """sha256("concord/epoch-key-commitment" || prev_epoch_be[8] || prev_key[32])."""
    _assert32("prev_key", prev_key)
    return hashlib.sha256(
        LABEL_EPOCH_COMMITMENT.encode() + prev_epoch.to_bytes(8, "big") + prev_key
    ).digest()


# ── Schnorr signing (BIP-340), for grants and seals ─────────────────────────

def schnorr_sign(message32: bytes, sk: bytes) -> bytes:
    return PrivateKey(sk).sign_schnorr(message32)
